apiVersion: v1  
kind: Namespace  
metadata:  
  name: harness-delegate-custom  
  
---  
  
apiVersion: rbac.authorization.k8s.io/v1  
kind: ClusterRoleBinding  
metadata:  
  name: harness-delegate-custom-cluster-admin  
subjects:  
  - kind: ServiceAccount  
    name: default  
    namespace: harness-delegate-custom  
roleRef:  
  kind: ClusterRole  
  name: cluster-admin  
  apiGroup: rbac.authorization.k8s.io  
  
---  
  
apiVersion: v1  
kind: Secret  
metadata:  
  name: custom-delegate-account-token  
  namespace: harness-delegate-custom  
type: Opaque  
data:  
  DELEGATE_TOKEN: "MzlkODFkMDZlMWZiZjU1MGE3OWU4YTlhYmFjYjcyZGI="  
  
---  
apiVersion: apps/v1  
kind: Deployment  
metadata:  
  labels:  
    harness.io/name: custom-delegate  
  name: custom-delegate  
  namespace: harness-delegate-custom  
spec:  
  replicas: 1  
  selector:  
    matchLabels:  
      harness.io/name: custom-delegate  
  template:  
    metadata:  
      labels:  
        harness.io/name: custom-delegate  
      annotations:  
        prometheus.io/scrape: "true"  
        prometheus.io/port: "3460"  
        prometheus.io/path: "/api/metrics"  
    spec:  
      terminationGracePeriodSeconds: 600  
      restartPolicy: Always  
      securityContext:  
        fsGroup: 1001  
        runAsUser: 1001  
      containers:  
      - image: harness/delegate:23.01.78102.minimal  
        imagePullPolicy: Always  
        name: delegate  
        ports:  
          - containerPort: 8080  
        resources:  
          limits:  
            cpu: "0.5"  
            memory: "2048Mi"  
          requests:  
            cpu: "0.5"  
            memory: "2048Mi"  
        livenessProbe:  
          httpGet:  
            path: /api/health  
            port: 3460  
            scheme: HTTP  
          initialDelaySeconds: 10  
          periodSeconds: 10  
          failureThreshold: 2  
        startupProbe:  
          httpGet:  
            path: /api/health  
            port: 3460  
            scheme: HTTP  
          initialDelaySeconds: 30  
          periodSeconds: 10  
          failureThreshold: 15  
        envFrom:  
        - secretRef:  
            name: custom-delegate-account-token  
        env:  
        - name: JAVA_OPTS  
          value: "-Xms64M"  
        - name: ACCOUNT_ID  
          value: p5ngBQg2RzeP1y3pHFOv2Q  
        - name: MANAGER_HOST_AND_PORT  
          value: https://app.harness.io/gratis  
        - name: DEPLOY_MODE  
          value: KUBERNETES  
        - name: DELEGATE_NAME  
          value: custom-delegate  
        - name: DELEGATE_TYPE  
          value: "KUBERNETES"  
        - name: DELEGATE_NAMESPACE  
          valueFrom:  
            fieldRef:  
              fieldPath: metadata.namespace  
        - name: INIT_SCRIPT  
          value: ""  
        - name: DELEGATE_DESCRIPTION  
          value: ""  
        - name: DELEGATE_TAGS  
          value: ""  
        - name: NEXT_GEN  
          value: "true"  
        - name: CLIENT_TOOLS_DOWNLOAD_DISABLED  
          value: "true"  
        - name: LOG_STREAMING_SERVICE_URL  
          value: "https://app.harness.io/gratis/log-service/"  
        volumeMounts:  
        - mountPath: /opt/harness-delegate/client-tools  
          name: client-tools  
      initContainers:  
      - name: install-kubectl  
        image: curlimages/curl  
        command: ['sh', '-c', "mkdir -m 777 -p /client-tools/kubectl/v1.13.2 \  
                                && curl -#s -L -o /client-tools/kubectl/v1.13.2/kubectl https://app.harness.io/public/shared/tools/kubectl/release/v1.13.2/bin/linux/amd64/kubectl \  
                                && chmod +x /client-tools/kubectl/v1.13.2/kubectl"]  
        args:  
          - chown 1001 /client-tools;  
        volumeMounts:  
        - mountPath: /client-tools  
          name: client-tools  
      - name: install-helm3  
        image: curlimages/curl  
        command: ['sh', '-c', "mkdir -m 777 -p /client-tools/helm/v3.8.0 \  
                                && curl -#s -L -o /client-tools/helm/v3.8.0/helm https://app.harness.io/public/shared/tools/helm/release/v3.8.0/bin/linux/amd64/helm \  
                                && chmod +x /client-tools/helm/v3.8.0/helm"]  
        args:  
          - chown 1001 /client-tools;  
        volumeMounts:  
        - mountPath: /client-tools  
          name: client-tools  
      volumes:  
      - name: client-tools  
        emptyDir: {}  
  
---  
  
apiVersion: v1  
kind: Service  
metadata:  
  name: delegate-service  
  namespace: harness-delegate-custom  
spec:  
  type: ClusterIP  
  selector:  
    harness.io/name: custom-delegate  
  ports:  
    - port: 8080  
  
---  
  
kind: Role  
apiVersion: rbac.authorization.k8s.io/v1  
metadata:  
  name: upgrader-cronjob  
  namespace: harness-delegate-custom  
rules:  
  - apiGroups: ["batch", "apps", "extensions"]  
    resources: ["cronjobs"]  
    verbs: ["get", "list", "watch", "update", "patch"]  
  - apiGroups: ["extensions", "apps"]  
    resources: ["deployments"]  
    verbs: ["get", "list", "watch", "create", "update", "patch"]  
  
---  
  
kind: RoleBinding  
apiVersion: rbac.authorization.k8s.io/v1  
metadata:  
  name: custom-delegate-upgrader-cronjob  
  namespace: harness-delegate-custom  
subjects:  
  - kind: ServiceAccount  
    name: upgrader-cronjob-sa  
    namespace: harness-delegate-custom  
roleRef:  
  kind: Role  
  name: upgrader-cronjob  
  apiGroup: ""  
  
---  
  
apiVersion: v1  
kind: ServiceAccount  
metadata:  
  name: upgrader-cronjob-sa  
  namespace: harness-delegate-custom  
  
---  
  
apiVersion: v1  
kind: Secret  
metadata:  
  name: custom-delegate-upgrader-token  
  namespace: harness-delegate-custom  
type: Opaque  
data:  
  UPGRADER_TOKEN: "MzlkODFkMDZlMWZiZjU1MGE3OWU4YTlhYmFjYjcyZGI="  
  
---  
  
apiVersion: v1  
kind: ConfigMap  
metadata:  
  name: custom-delegate-upgrader-config  
  namespace: harness-delegate-custom  
data:  
  config.yaml: |  
    mode: Delegate  
    dryRun: false  
    workloadName: custom-delegate  
    namespace: harness-delegate-custom  
    containerName: delegate  
    delegateConfig:  
      accountId: p5ngBQg2RzeP1y3pHFOv2Q  
      managerHost: https://app.harness.io/gratis  
  
---  
  
apiVersion: batch/v1 
kind: CronJob  
metadata:  
  labels:  
    harness.io/name: custom-delegate-upgrader-job  
  name: custom-delegate-upgrader-job  
  namespace: harness-delegate-custom  
spec:  
  schedule: "0 */1 * * *"  
  concurrencyPolicy: Forbid  
  startingDeadlineSeconds: 20  
  jobTemplate:  
    spec:  
      suspend: false  
      template:  
        spec:  
          serviceAccountName: upgrader-cronjob-sa  
          restartPolicy: Never  
          containers:  
          - image: harness/upgrader:latest
            name: upgrader  
            imagePullPolicy: Always  
            envFrom:  
            - secretRef:  
                name: custom-delegate-upgrader-token  
            volumeMounts:  
              - name: config-volume  
                mountPath: /etc/config  
          volumes:  
            - name: config-volume  
              configMap:  
                name: custom-delegate-upgrader-config  
